spring:
  datasource:
    username: abc
    password: abc
    url: jdbc:h2:mem:sbms
    driver-class-name: org.h2.Driver
   
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 9090
 

